### ISSUE TITLE
마이페이지 - 하위 메뉴들 클릭했을때 전체적인 레이아웃은 그대로에 밑에 내용물만 바뀌어야 할것같아영

### ISSUE THREAD

**Issue by sossost** [fog-of-war/dev-fe#227]

**Comment by YubinShin** [comment]
![image](https://github.com/fog-of-war/dev-fe/assets/68121478/72061662-2208-4eb0-b9ac-9cd5e79df2af)
![image](https://github.com/fog-of-war/dev-fe/assets/68121478/d72cb318-68bf-4599-9db5-dcc173b0ac41)
![image](https://github.com/fog-of-war/dev-fe/assets/68121478/2f46223b-0c47-496b-a372-c84ae2beb61b)
![image](https://github.com/fog-of-war/dev-fe/assets/68121478/2ab48c3b-e662-4565-b618-2e87ef56fa37)
